### ISSUE TITLE
No Error Messages

### ISSUE THREAD

**Issue by Black-Photon** [dfranx/ShaderDebugger#3] opened 2020-02-02 02:53 UTC
As it is, most errors when calling library functions are segfaults. As a C++ library, it would be much more helpful to have exceptions when debugging code, and making fault-tolerant programs.

**Comment by dfranx** [comment] 2020-02-02 11:21
True.. Making fault-tolerant programs is important. I will look into this more.

Though, I haven't experienced too many crashes in ShaderDebugger lately but if it does crash for you, please report it! I'd love to fix the cause of the issue.

**Comment by Black-Photon** [comment] 2020-02-02 13:50
Here's an example with the sample code:
```cpp
int main() {
    std::string src = "out vec4 outColour;\n"
                      "uniform float time;\n"
                      "\n"
                      "void main()\n"
                      "{\n"
                      "\tfloat colour = max(sin(time), -sin(time));\n"
                      "\toutColour = vec4(colour, colour, colour, 1);\n"
                      "}";

    sd::ShaderDebugger dbg;
    dbg.SetSource<sd::GLSLCompiler>(sd::ShaderType::Pixel, src, "main", NULL, sd::GLSL::Library());

    dbg.SetGlobalValue("time", 1.0f);

    while (dbg.Step() && dbg.GetCurrentLine() != 7);

    float colour = sd::AsFloat(*dbg.GetLocalValue("colour"));
    printf("outColour = %.2f;\n", colour);

    while (dbg.Step());

    glm::vec3 outColour = sd::AsVector<4, float>(*dbg.GetGlobalValue("outColour"));
    printf("outColour = vec3(%.2f, %.2f, %.2f);\n", outColour.x, outColour.y, outColour.z);

    return 0;
}
```

You can get a segfault by any of:
- Invalid Program (Add extra curly brace at end of `src`)
- Invalid Entry (Change `main` to `main2` when setting source)
- Invalid Local Variable (Try and read `colour` on an earlier line number before it exists)
- Invalid Access Method; Try to set variable using:
`dbg.SetGlobalValue("rgb", "GLSL", glm::vec4(1.0f, 0.5f, 1.0f, 1.0f));`

And an assertion failure by:
- Invalid Type Conversion (Try and read as a Vector3)

Most of them are caused by some null value having variables accessed or memory called:
- `m_prog` may not exist in `SetGlobalValue`
- `m_stepper` may not exist in `Step`
- Parameter to `ToFloat` may not exist (though admittedly the programmer is at fault here)
- `objInfo` may not exist in `SetGlobalValue`

**Comment by dfranx** [comment] 2020-02-02 14:21
Thank you so much for this detailed report!
I am still not sure where and why I should add exceptions, though. Sorry, I've never actually used them too much.
I need your input on this, because:

> Invalid Program (Add extra curly brace at end of src)
> Invalid Entry (Change main to main2 when setting source)

In these two cases the `SetSource` will return `false` and the programmer can check if compilation process succeeded with a simple `if` statement.

> Invalid Local Variable (Try and read colour on an earlier line number before it exists)

The `GetLocalValue` will return `nullptr`. The programmer can then check if the variable exists. The same thing is valid for `GetGlobalValue`. I've used this 'property' in this simple tool I've written that uses ShaderDebugger:
https://github.com/dfranx/sdbg/blob/f4fc6d66fa876d9349dad1cc00271bbb525b2fa7/main.cpp#L445-L447

> Invalid Access Method

This is true, I forgot that this could happen. But I guess I could just make `SetGlobalValue` be boolean function and return `false` if the operation didn't succeed.

> Invalid Type Conversion (Try and read as a Vector3)

Sorry, could you elaborate this more? I am not sure what you've meant with this.. Try and read what as  a vector?


Also, a few tips:
This
```c++
dbg.Jump(7);
```
can be used instead of
```c++
while (dbg.Step() && dbg.GetCurrentLine() != 7);
```
Also this
```c++
dbg.Continue();
```
can be used instead of
```c++
while (dbg.Step());
```

**Comment by Black-Photon** [comment] 2020-02-02 16:03
Thanks for the response!

Admittedly I may have been following the example too closely - I didn't notice that the methods returned error checks. My concern was that segfaults immediately exit the program without any kind of feedback, so if there's some kind of bug in a derived program, it'll exit without the user/developer being able to easily diagnose where it may have gone wrong and how to fix it without getting out a debugger to back-trace the errors origin. However this is more of a convenience than a necessity.

Ideally they'd be checks at the start of the function for whether the data is valid, and throw an exception describing why the function failed inside. These can also be caught by parent libraries/applications to do other functionality - eg. showing the error in the GUI.

Alternatively some other libraries have error stores that hold the last error that has occurred, and silently fail any invalid operations, so during debugging you can use a function such as `last_error()` to find the problem, and the application will be able to continue.

Normally either approach would be implemented by adding checks for invalid inputs to functions and reporting these, ensuring the application is always in a functioning state.

> Invalid Type Conversion (Try and read as a Vector3)

I meant changing to this:
`glm::vec3 outColour = sd::AsVector<3, float>(*dbg.GetGlobalValue("outColour"));`
So it's trying to read the `vec4` as a `vec3`

And thanks for the tips, those methods are a lot more convenient than mine. This is looking like a really nice library.

**Comment by dfranx** [comment] 2020-02-03 15:22
> Ideally they'd be checks at the start of the function for whether the data is valid
> describing why the function failed inside

Yeah, I've used assert for that, I think it is more appropriate. It also tells the programmer the reason why a function failed.

> So it's trying to read the vec4 as a vec3

Oh okay, thanks. That was my mistake. I've fixed it, now it "converts" the vec4 to vec3. Basically it copies max available fields to the vector.

Thanks for reporting these and openning a pull request!
I will close this now since I've added the error messages.

**Closed as completed by dfranx** 2020-02-03 15:22 UTC

**Comment by dfranx** [comment] 2020-02-03 16:42
Also, forgot to add... The value of "rgb" may not be set because it was not defined as a global variable in shader. To define a variable manually, call ShaderDebugger::AddGlobal(name).
For example:
```c++
dbg.AddGlobal("rgb");
// now you can set any value you want to
```
